version: '3.7'

services:
  postgresql:
    image: postgres:13.1
    restart: unless-stopped
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgresql_dev/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgresqlPassword
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "1"



volumes:
  postgres_data:
